all: 
	python bibconvert.py --suffix jekyll --highlight "Yibo Lin" --highlight "Lin, Yibo" --input Top.bib --input publications.bib > ../_pages/publications.md
	python bibconvert.py --suffix cvjekyll --highlight "Yibo Lin" --highlight "Lin, Yibo" --input Top.bib --input publications.bib > ../_includes/publications_cv.md
