all:
	python ../ref/bibconvert.py --suffix cv_cn --highlight "Yibo Lin" --highlight "Lin, Yibo" --input ../ref/Top.bib --input ../ref/publications.bib > doc/publication.tex
	xelatex cv_yibo.tex

clean:
	rm *.aux *.log *.nav *.out *.snm *.toc
